analyze_documentation:
  description: >
    Analyze the provided API documentation and extract relevant information about
    the endpoint that matches the user's request: {user_query}
    
    Use the RAG tool to search through the documentation.
  expected_output: >
    Detailed information about the relevant API endpoint including:
    - Endpoint URL
    - HTTP method
    - Required parameters
    - Authentication requirements
    - Expected responses

implement_api_call:
  description: >
    Using the API documentation analysis, implement a Python code snippet that
    makes the API call.
    If all the infomation is not provided, ask user for more infomation.
    Use the PythonREPLTool create the code and execute it.
  expected_output: >
    Working Python code that implements the API call with proper error handling
    and authentication.
